### ISSUE TITLE
RSS Feed linking to pages that don't exist

### ISSUE THREAD

**Issue by lily-mara** [RustMagazine/rustmagazine#25]
I'm subscribed to Rust Magazine via the RSS feed, and I've noticied several posts come across my feed that link back to pages on rustmagazine.org that 404 when I try to load them. For example, if I load [https://rustmagazine.org/feed.xml](https://rustmagazine.org/feed.xml) right now, it shows me an entry titled "How I contribute to Rust Compiler" that links to [https://rustmagazine.org/i/contribute-to-rustc](https://rustmagazine.org/i/contribute-to-rustc), which 404s.

<img width="1042" alt="screenshot of rustmagazine rss feed showing the 'how I contribute to Rust Compiler' story linking to https://rustmagazine.org/i/contribute-to-rustc" src="https://user-images.githubusercontent.com/6109875/216134748-73453ff0-1641-4c80-a1b1-575d9fe96c96.png">

<img width="985" alt="screenshot of browser navigated to https://rustmagazine.org/i/contribute-to-rustc showing a github pages http 404 error response" src="https://user-images.githubusercontent.com/6109875/216134793-e2d0e93d-7118-415d-986d-678473033255.png">

**Comment by Folyd** [comment]
Hi, @lily-mara. Thanks for the feedback. We haven't released Issue 1. The reason why article 404 is because we set `publish` to `false`. Maybe we also should not render the RSS feed.xml, I'll fix it later.

https://github.com/RustMagazine/rustmagazine/blob/11c536588390a0c6f346952e8b0b748f4fa61792/content/issue-1/zine.toml#L40

**Comment by Folyd** [comment]
I'll close this issue since it has been fixed.
