### ISSUE TITLE
The font-weight for title seems too large that hard to read

### ISSUE THREAD

**Issue by Xuanwo** [RustMagazine/rustmagazine#38]
As described in the title, the font weight is too large.

![image](https://user-images.githubusercontent.com/5351546/217145180-9f35e13f-f7d0-4881-8f52-2faaa403677c.png)

After remove `font-weight: 800`:

![image](https://user-images.githubusercontent.com/5351546/217145393-d4358047-cf71-447d-a8bf-3d9e853dcbff.png)

---

What do you think?

**Comment by Folyd** [comment]
Yes, we need to improve this. Thanks.

**Comment by Folyd** [comment]
> From [reddit](https://www.reddit.com/r/rust/comments/10v9vso/comment/j7k3y6t/?utm_source=share&utm_medium=web2x&context=3):

This font gets double-bolded :D – Alfa Slab One is already bold, and then font-weight: 800 makes the browser "bold it even more" ([fun fact: Rust blog also had the same issue](https://github.com/rust-lang/blog.rust-lang.org/issues/309)). So instead of dimming the font-weight of titles, you should instead just tell the browser that Alfa Slab One is already bold:

@font-face {
  font-family: 'Alfa Slab One';
  font-style: normal;
  font-weight: 800; ← change from 400
(setting weight 400 for title would also work, but would have a side-effect of disabling bold when fallback font is used)
